---
- name: install php repository
  apt_repository: repo="ppa:ondrej/php" update_cache=yes

- name: install PHP
  become: yes
  apt: name=php7.2 state=latest update_cache=yes

- name: install PHP packages
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php7.2-fpm
    - php7.2-cli
    - php7.2-common
    - php7.2-curl
    - php7.2-json
    - php7.2-gd
    - php7.2-odbc
    - php7.2-pgsql
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-xmlrpc
    - php7.2-opcache
    - php7.2-intl
    - php7.2-bz2
    - php7.2-xml

# https://github.com/oerdnj/deb.sury.org/issues/755
- name: install libpcre3
  become: yes
  apt: name=libpcre3 state=latest update_cache=yes

- name: restart php-fpm
  become: yes
  service: name=php7.2-fpm state=restarted
